### ISSUE TITLE
Package base into adminhtml folder

### ISSUE THREAD

**Issue by VincentMarmiesse** [jreinke/magento-suffix-static-files#1]
Hello, 
I am using your extension and it works perfectly!
But I noticed the adminhtml template is into base package (adminhtml/base/default), but base package does not exist by default.
It should be into default package, shouldn't it?

Vincent

**Comment by jreinke** [comment]
Hello,

It's just in base package to allow multiple levels back in case of design overriding but it could be in default package you're right :)
